### ISSUE TITLE
memcached process's open fd limit is 1024

### ISSUE THREAD

**Issue by mamoit** [docker-library/memcached#18]
```
$ docker run --rm -d --name memtest memcached
$ docker exec memtest cat /proc/1/limits | grep open
Max open files            1024                 1024                 files
```
While the memcache user actually has a higher limit.
```
$ docker exec memtest ulimit -n
1048576
```
This is way too little for a busy memcache server (I'm hitting the limit all the time).

**Comment by mamoit** [comment]
Got it...
```
-c <num>
    Use <num> max simultaneous connections; the default is 1024. 
```

**Comment by mamoit** [comment]
One of those cases of rtfm... Thanks @solict

**Comment by tianon** [comment]
Glad you got it figured out!  There's also the `--ulimit` option to `docker run` which might be helpful. :+1:

**Comment by mamoit** [comment]
I was actually using it through the stable/memcached kubernetes helm chart, which uses this docker image, so ulimit was not an option.
I actually need to change the chart.

Thanks anyway :smile:
