### ISSUE TITLE
Memcached is not running

### ISSUE THREAD

**Issue by eau-de-la-seine** [docker-library/memcached#34]
Hi,

First, I've pull memcached:
`docker pull memcached
`

Then, like in the [presentation page](https://hub.docker.com/_/memcached/), I've runned it:
`docker run --name my-memcache -d memcached
`

A `docker ps -a` shows me this:
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                                                         NAMES
43812fe9a62b        memcached           "docker-entrypoint.s…"   About an hour ago   Up About an hour    11211/tcp                                                                                                     my-memcache
```

But a `netstat -nlp` shows me that the **11211 port is not occupied**.

My Docker version is:

> Docker version 17.12.0-ce, build c97c6d6

My OS version is:

> Distributor ID: Ubuntu
> Release:        16.04
> Codename:       xenial

Thanks,

**Comment by wglambert** [comment]
You need the `-P` flag to expose default ports to the host, or `-p port:port` to manually assign exposed ports in host->container format.

**Comment by eau-de-la-seine** [comment]
I have already tried `-p port:port`. By the way this has worked: `docker run -i -d -p 11211:11211 memcached` for me. I think that the problem comes from a **conflict** between `-p port:port` and the other options `--name my-memcache -d memcached`

**Comment by Chiranjeevignaidu** [comment]
I am getting this output whenever I am using the docker instance: 
```
echo "stats settings" | ncat -v 127.0.0.1 11211
Ncat: Version 7.94 ( https://nmap.org/ncat )
Ncat: Connected to 127.0.0.1:11211.
Ncat: 16 bytes sent, 0 bytes received in 0.45 seconds.
```
These are all the commands I used:

- `docker run -i -d -p 11211:11211 memcached:bookworm`
- `docker run --network="host" --name my-memcached -p 11211:11211 -d memcached:bookworm memcached -l 0.0.0.0,::1 -m 64 -c 1024 -vv`
- `docker run --network="host" --name my-memcached -p 11211:11211 -d memcached:bookworm memcached -l 0.0.0.0 -m 64 -c 1024 -vv`

The config files I used:
```
# memcached.conf
-l 0.0.0.0   # Listen on all interfaces
-m 64        # Memory allocation for Memcached in MB
-c 1024      # Maximum simultaneous connections
-vv          # Verbose output
```
Other than this I have no clue what to do? Please help.
