### ISSUE TITLE
Use numeric uid in USER command

### ISSUE THREAD

**Issue by praseodym** [docker-library/memcached#36]
Using a numeric uid instead of a username in the `USER` command allows platforms like Kubernetes to validate that the container will run as non-root (uid >0) before starting it. This is because a username could actually alias to uid 0 (root), whereas a non-zero uid is never the root user.

**Comment by donita85** [comment]
+1

**Comment by tianon** [comment]
As I've noted in https://github.com/docker-library/memcached/pull/37#issuecomment-435214592:

> I'm still not sold on the tangible benefit to users of being explicit about the exact UID we run as in that way (since what we do now is equivalent and the image supports running as an arbitrary UID anyhow, so paranoid users can trivially choose their own UID, or do crazy things like randomize the UID like OpenShift likes to do).
