### ISSUE TITLE
Should indicate which port are exposed by default

### ISSUE THREAD

**Issue by mapleeit** [docker-library/memcached#44]
https://hub.docker.com/_/memcached
Should indicate which port are exposed by default. For example: https://hub.docker.com/_/redis

![image](https://user-images.githubusercontent.com/4194287/50421289-9fb44500-0878-11e9-9170-8dbfe5f4b000.png)

**Comment by yosifkit** [comment]
I would rather go the other direction and delete any mention of `EXPOSE` in the official images documentation. The image itself documents what ports are "exposed" and can be seen with a `docker image inspect memcached`.

```console
$ docker image inspect memcached | jq '.[].ContainerConfig.ExposedPorts'
{
  "11211/tcp": {}
}
```

**Comment by tianon** [comment]
Indeed, I'd tend to agree, especially since 11211 is the official well-known memcached default port. :+1:
