### ISSUE TITLE
Fixing in Dockerfile

### ISSUE THREAD

**Issue by thatsk** [docker-library/memcached#50]
Hello team due to some issue we need to update Docker file for docker-entrypoint.sh
following instruction should be added in alpine container.
```YAML#for Fixing entrypoint issue
RUN chmod 777 /usr/local/bin/docker-entrypoint.sh \
    && ln -s /usr/local/bin/docker-entrypoint.sh

**Comment by thatsk** [comment]
https://github.com/docker-library/postgres/issues/296

**Comment by tianon** [comment]
As you pointed out, this is the same issue as that one, and the solutions I outlined in https://github.com/docker-library/postgres/issues/296#issuecomment-308735942 are still recommended:

Either use `git clone` or manually apply `chmod +x` to your local file before invoking `docker build`.
