### ISSUE TITLE
1.5.19 warm cache start up does not work

### ISSUE THREAD

**Issue by igor875126** [docker-library/memcached#53]
Hey,

## Issue description
if you pull your docker image 1.5.19-alpine and try to use warm cache start up option, you will notice it ends up in error:
```ftruncate failed: Bad file descriptor```
```Aborted```

## How to reproduce
```bash
docker run -it --rm memcached:1.5.19-alpine sh
memcached -e /test
```

**Comment by yosifkit** [comment]
That would be expected and is the same in the debian image as well.  The `memcache` user doesn't have write access to `/`.  Try giving `-e` a place that it has write access, e.x. `/tmp/test`
