### ISSUE TITLE
v1.6.3 Docker Image? 

### ISSUE THREAD

**Issue by 3XC1T3D** [docker-library/memcached#57]
When will be the official 1.6.3 Docker Image available?

Best regards

**Comment by tianon** [comment]
There was a slight bug in our version scraping which I've now fixed -- I'll make sure we get a PR up to https://github.com/docker-library/official-images today. :+1:

**Comment by 3XC1T3D** [comment]
Thank You @tianon. Looking forward to download version 1.6.3 later ;)

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/7714 :+1:

**Comment by 3XC1T3D** [comment]
Sry @tianon but am i missing something? Or why is there still no 1.6.3 Tag available on hub.docker.com?
