### ISSUE TITLE
Wish to support authorization through environment variables

### ISSUE THREAD

**Issue by Mr-LiuDC** [docker-library/memcached#70]
Wish to support authorization through environment variables.
like this:

```
docker run -d \
    --name memcached \
    -p 11211:11211 \
    -e MEMCACHED_USERNAME=myusername \
    -e MEMCACHED_PASSWORD=mypassword
```

**Comment by tianon** [comment]
Unfortunately, this isn't something we're comfortable adding/maintaining on top of stock `memcached` (our experience doing so for other images has been extremely negative).

I would suggest that this be filed as a feature request with memcached upstream instead.  Alternatively, it shouldn't be too difficult to write and maintain your own script for this which gets added to an image that's `FROM` this one.
