### ISSUE TITLE
New images aren't signed via docker notary

### ISSUE THREAD

**Issue by rhuddleston** [docker-library/memcached#74]
export DOCKER_CONTENT_TRUST=1
docker pull memcached:1.6.9-alpine

Everything works fine with the above

for 1.6.10 and above:

$ docker pull memcached:1.6.12-alpine
No valid trust data for 1.6.12-alpine

**Comment by yosifkit** [comment]
Duplicate of https://github.com/docker-library/official-images/issues/6838
