### ISSUE TITLE
where I can get information about this image environment variables

### ISSUE THREAD

**Issue by donny26utama** [docker-library/memcached#89]
I have read on docker hub, but cannot get information about the available environment variables

**Comment by tianon** [comment]
Our entrypoint script (which is where image-specific environment variables might be implemented, if they were) is very short:

https://github.com/docker-library/memcached/blob/d3a51632e123ddcbf1b1e06e6cefdaa65f27b29a/debian/docker-entrypoint.sh#L1-L9

In other words, there are _no_ environment variables specific to this image, and any behavior in `memcached` controlled by environment variables in this image is actually behavior in `memcached` itself, which might make it easier to search for (even if the answer still ends up being "none" :see_no_evil:).
